### ISSUE TITLE
Meaning of the is_raw option in the output plugin

### ISSUE THREAD

**Issue by guilhemmarchand** [jianchen2580/logstash-output-splunk#2]
Hi @jianchen2580 !

I am currently testing and benchmarking your great plugin performances compared to the usage of the http output builtin Logstash plugin to send data to Splunk HEC, with great success and an impressive gain in performance.

To give you an idea in labs, the http output plugin would struggle at 200K records consumed per minute in that setup, where the same setup would reach up to 1 / 1.5M of records per minute and successfully reach the Splunk instance resources limitations.

My question is regarding the purpose of the following option:

`is_raw => true` 

I could not find an explanation for its purpose in the code, from a Splunk perspective I would perhaps understand that false would be intended to use the HEC event collector endpoint rather than the raw endpoint, but this is an assumption.

Does it currently change anything, or was that intended for later implementation?

Thanks in advance, and thanks for developing this great work!

Cheers,

Guilhem

**Comment by jianchen2580** [comment]
so far `is_raw => true` is redundant, and your can set url to raw endpoint directly, e.g.
`url   => "http://example.com:9999/services/collector/raw"`

**Comment by guilhemmarchand** [comment]
Thanks @jianchen2580 for your quick reply, this answers my question then ;-)
